#!/usr/bin/env python

import envoy

def main():
    """Main function for installing project's dependencies."""

    install = False
    try:
        # Check for requirements File
        with open('requirements.txt') as file:
            print("Requirements detected!")

            # Inform the User after dependencies detection
            print('Found {} dependencies. Please wait, installing!'.format(
                sum(1 for line in file)))
        install = True
    except FileNotFoundError:
        print("Please add requirements.txt file")

    if install:
        # Install the packages from requirements.txt
        command = 'pip install -r requirements.txt'
        print(envoy.run(command).std_out)
        print("All dependencies installed!")


if __name__ == '__main__':
    main()
