#!/usr/bin/env python

import envoy

def main():

    try:
        # Check for requirements File
        file = open('requirements.txt')
        print("Requirements detected!")
        file.close()
    except FileNotFoundError:
        print("Please add requirements File")

    # Inform the User after dependencies detection
    print('Found {} dependencies. Please wait, Installing!'.format(sum(1 for line in open('requirements.txt'))))

    # Install the packages from requirements.txt
    command = 'pip install -r requirements.txt'
    print(envoy.run(command).std_out)

    # Show success !
    print('Installed!')


if __name__ == '__main__':
    main()
