#!/usr/bin/env python

import envoy

def main():

    # Inform the User after dependency detection
    print('Found {} dependencies, Installing!'.format(sum(1 for line in open('requirements.txt'))))

    # Install the packages from requirements.txt
    command = 'pip install -r requirements.txt'
    print(envoy.run(command).std_out)
    print('Installed!')


    # Show success !

if __name__ == '__main__':
    main()
